name: test_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: 2.5.2
  go_router: ^14.1.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  sembast: ^3.7.1+2
  sqflite: ^2.3.3+1
  sqflite_common_ffi: any
  sqflite_common_ffi_web: any
  stack_exchange:
    git:
     url: https://github.com/kkh95x/stack_exchange.git

  
dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router_builder: ^2.3.0
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
